"""Protocols, Enums, and Dataclasses for Recovery Decision & Next Best Action Engine."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from app.services.customer_intelligence import CustomerHistoricalFeatures


class ActionType(str, Enum):
    """Controlled vocabulary for recovery actions."""

    RETRY_PAYMENT = "RETRY_PAYMENT"
    SEND_PAYMENT_LINK = "SEND_PAYMENT_LINK"
    SEND_WHATSAPP_REMINDER = "SEND_WHATSAPP_REMINDER"
    VOICE_OUTREACH = "VOICE_OUTREACH"
    WAIT = "WAIT"
    ESCALATE = "ESCALATE"
    NO_ACTION = "NO_ACTION"


class ActionStatus(str, Enum):
    """Lifecycle status of a recovery action."""

    RECOMMENDED = "RECOMMENDED"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ChannelType(str, Enum):
    """Communication and intervention channels."""

    GATEWAY = "GATEWAY"
    EMAIL = "EMAIL"
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
    VOICE = "VOICE"
    SYSTEM = "SYSTEM"
    MANUAL = "MANUAL"


@dataclass
class DecisionContext:
    """Consolidated situational context consumed by the Recovery Decision Engine."""

    case_id: str
    case_type: str
    amount_at_risk: Decimal
    currency: str
    case_age_hours: float
    retry_count: int
    diagnosis_category: str
    diagnosis_confidence: float
    risk_score: float
    recovery_probability: float
    customer_features: Optional[CustomerHistoricalFeatures] = None
    payment_method: Optional[str] = None
    bank: Optional[str] = None
    customer_phone_available: bool = False
    customer_email_available: bool = False
    promise_to_pay_active: bool = False
    current_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_intervention_time: Optional[datetime] = None
    previous_action_types: List[str] = field(default_factory=list)
    previous_action_outcomes: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ActionCandidate:
    """Scored candidate recovery action."""

    action_type: str
    channel: str
    score: float  # Normalized decision score (0.0 to 1.0)
    confidence: float  # Decision confidence (0.0 to 1.0)
    reason: str
    supporting_factors: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_type": self.action_type,
            "channel": self.channel,
            "score": round(self.score, 4),
            "confidence": round(self.confidence, 4),
            "reason": self.reason,
            "supporting_factors": self.supporting_factors,
        }


@dataclass
class RecommendationResult:
    """Output generated by a Recovery Decision Engine."""

    recommended_action: str
    channel: str
    score: float
    confidence: float
    reason: str
    supporting_factors: List[str]
    alternatives: List[Dict[str, Any]]
    decision_engine_version: str


class RecoveryDecisionEngine(Protocol):
    """Protocol for recovery decision engines (Rule-based or ML)."""

    version: str

    def recommend(self, context: DecisionContext) -> RecommendationResult:
        """Evaluate context and produce next best action recommendation."""
        ...
